// client/src/components/Header.vue
<script setup lang="ts">
// import SearchFilter from './filter/SearchFilter.vue'
</script>

<template>
  <div>
    <header class="h-40 md:h-[250px] w-f ull bg-cyan-400">
      <div class="relative w-full h-full">
        <img
          src="@/assets/img/bg-header-desktop.svg"
          class="absolute inset-0 w-full lg:hidden object-cover object-right h-full"
          alt="bg-header-mobile"
        />
        <img
          src="@/assets/img/bg-header-desktop.svg"
          class="absolute inset-0 hidden lg:flex h-full"
          alt="bg-header-desktop"
        />
      </div>
    </header>
  </div>
</template>

// MERN/client/src/components/layout/Header.tsx
import Navbar from '../common/Navbar';
import bgHeaderDesktop from '../../assets/img/bg-header-desktop.svg';

interface HeaderProps {
  children?: React.ReactNode;
}

const Header = ({ children }: HeaderProps) => {
  return (
    <div>
      <Navbar />
      <header className="h-40 md:h-[250px] w-full bg-cyan-400">
        <div className="relative w-full h-full">
          <img
            src={bgHeaderDesktop}
            className="absolute inset-0 w-full lg:hidden object-cover object-right h-full"
            alt="bg-header-mobile"
          />
          <img
            src={bgHeaderDesktop}
            className="absolute inset-0 hidden lg:flex h-full"
            alt="bg-header-desktop"
          />
        </div>
      </header>
      {children}
    </div>
  );
};

export default Header;
