// client/src/components/filter/Filter.vue
<script setup lang="ts">
import { computed, onMounted } from 'vue'
import { storeToRefs } from 'pinia'
import { useFilterStore } from '@/stores/FilterStore'
import FilterBtn from './FilterBtn.vue'
import { levelsOptions, skillsOptions, marketsOptions, rolesOptions } from '@/constants/filters'

const filterStore = useFilterStore()
const { groupedFilters, skills, markets, companySizes, contract, roles, workType, level } =
  storeToRefs(filterStore)

onMounted(() => {
  console.log('On mount filter data', {
    workType: workType.value,
    level: level.value,
    skills: skills.value,
    markets: markets.value,
    roles: roles.value,
    companySizes: companySizes.value,
    contract: contract.value,
  })
  console.log('Grouped filters', groupedFilters.value)
})

const formatSalary = (salary: number) => {
  if (salary >= 1000000) return `${(salary / 1000000).toFixed(0)}M`
  if (salary >= 1000) return `${(salary / 1000).toFixed(0)}k`
  return salary.toString()
}

const selectedBtns = computed(() => {
  const filterData = (groupedFilters.value ?? []) as Array<Record<string, unknown>>
  const btns: Array<{ text: string; key: string; value: unknown }> = []

  for (const item of filterData) {
    const entries = Object.entries(item || {})
    const first = entries[0]
    if (!first) continue
    const [key, value] = first

    if (key === 'search' || key === 'location' || key === 'sortByCompany' || key === 'timeframe')
      continue

    switch (key) {
      case 'workType':
        btns.push({
          text: String(value).replace(/^./, (c) => c.toUpperCase()),
          key: 'workType',
          value: '',
        })
        break

      case 'level':
        const lang = levelsOptions.find((opt) => opt.value === value)
        btns.push({ text: lang?.label || String(value), key: 'level', value: '' })
        break

      case 'minSalary':
      case 'maxSalary':
        const foundMin = filterData.find((it) => it && 'minSalary' in it) as any
        const foundMax = filterData.find((it) => it && 'maxSalary' in it) as any
        const foundCurrency = filterData.find((it) => it && 'currency' in it) as any
        const foundTimeframe = filterData.find((it) => it && 'timeframe' in it) as any

        const min = foundMin?.minSalary as number | undefined
        const max = foundMax?.maxSalary as number | undefined
        const currency = (foundCurrency?.currency as string) || ''
        const timeframe = (foundTimeframe?.timeframe as string) || ''

        let salaryText = ''
        if (min && max)
          salaryText = `${currency}${formatSalary(min)}-${currency}${formatSalary(max)}`
        else if (min) salaryText = `>${currency}${formatSalary(min)}`
        else if (max) salaryText = `<${currency}${formatSalary(max)}`

        if (salaryText && !btns.some((b) => b.key === 'salary')) {
          const capitalizedTimeframe = timeframe
            ? timeframe.replace(/^./, (c) => c.toUpperCase())
            : ''
          const salaryWithTimeframe = capitalizedTimeframe
            ? `${salaryText} per ${capitalizedTimeframe}`
            : salaryText
          btns.push({
            text: salaryWithTimeframe,
            key: 'salary',
            value: { minSalary: undefined, maxSalary: undefined, currency: '', timeframe: '' },
          })
        }
        break

      case 'skills':
      case 'markets':
      case 'companySizes':
      case 'contract':
      case 'roles':
        // Map stored values back to a human-friendly label.
        const arrays: Record<string, string[] | undefined> = {
          skills: skills.value,
          markets: markets.value,
          companySizes: companySizes.value,
          contract: contract.value,
          roles: roles.value,
        }
        const arr = arrays[key] as string[] | undefined
        if (typeof value === 'number') {
          btns.push({ text: value === 1 ? (arr?.[0] ?? '') : `${key} • ${value}`, key, value: [] })
        } else {
          // For skills and markets, stored values may be normalized (e.g. 'javascript')
          let label = String(value)
          if (key === 'skills') {
            const found = skillsOptions.find(
              (s) => s.toLowerCase().replace(/\s+/g, '-') === String(value),
            )
            label = found ?? String(value)
          } else if (key === 'markets') {
            const found = marketsOptions.find(
              (m) => m.toLowerCase().replace(/\s+/g, '-') === String(value),
            )
            label = found ?? String(value)
          } else if (key === 'roles') {
            // roles are stored as plain labels
            const found = rolesOptions.find((r) => r === String(value))
            label = found ?? String(value)
          }
          btns.push({ text: label, key, value: [] })
        }
        break
    }
  }

  return btns
})

const removeBtn = (btnText: string) => {
  const btnToRemove = selectedBtns.value.find((btn) => btn.text === btnText)

  if (btnToRemove) {
    if (btnToRemove.key === 'salary') {
      // Clear salary fields in one call
      filterStore.setFilters({
        minSalary: undefined,
        maxSalary: undefined,
        currency: '',
        timeframe: '',
      })
    } else {
      const key = btnToRemove.key as keyof import('@/stores/FilterStore').FilterFields
      filterStore.setFilters({ [key]: btnToRemove.value } as any)
    }
  }
}

const clearAllBtns = () => {
  filterStore.resetFilters()
}
</script>

<template>
  <div :class="`${selectedBtns.length > 0 ? 'block' : 'hidden'} border-t pt-5`">
    <div class="w-full relative h-auto">
      <div class="flex flex-wrap gap-4">
        <FilterBtn :btns="selectedBtns.map((btn) => btn.text)" :removeBtn="removeBtn" />
      </div>
      <button
        class="absolute right-6 top-4 text-teal-600 font-semibold cursor-pointer hover:underline"
        @click="clearAllBtns"
      >
        Clear
      </button>
    </div>
  </div>
</template>

// MERN/client/src/components/filter/Filter.tsx
import { useMemo } from 'react';
import { useSelector, useDispatch } from 'react-redux';
import { RootState, AppDispatch } from '../../redux/store';
import { resetFilters, setFilters } from '../../redux/reducers/filterSlice';
import FilterBtn from './FilterBtn';
import { getSalaryDisplay } from '../../utils/salaryFormatter';
import {
  levelsOptions,
  skillsOptions,
  marketsOptions,
  rolesOptions,
} from '../../constants/filters';
import type { FilterState } from '../../redux/reducers/filterSlice';

function getGroupedFilters(state: FilterState): Array<Record<string, unknown>> {
  const data = Object.entries(state).filter(
    ([key]) => key !== 'selectedBtns' && key !== 'aiMode',
  );
  const mappedData = data
    .filter(
      ([, value]) =>
        value !== null &&
        value !== undefined &&
        !(Array.isArray(value) && value.length === 0) &&
        !(typeof value === 'string' && (value as string).trim() === ''),
    )
    .map(([key, value]) => {
      if (Array.isArray(value)) {
        if (value.length === 1) return { [key]: value[0] };
        if (value.length > 1) return { [key]: value.length };
      } else if (typeof value === 'string' || typeof value === 'number') {
        return { [key]: value };
      } else if (typeof value === 'boolean' && value === true) {
        return { [key]: value };
      }
      return null;
    })
    .filter(Boolean) as Array<Record<string, unknown>>;
  return mappedData;
}

const Filter = () => {
  const dispatch = useDispatch<AppDispatch>();
  const filters = useSelector((state: RootState) => state.filters);

  const selectedBtns = useMemo(() => {
    const filterData = getGroupedFilters(filters);
    const btns: Array<{ text: string; key: string; value: unknown }> = [];

    for (const item of filterData) {
      const entries = Object.entries(item ?? {});
      const first = entries[0];
      if (!first) continue;
      const [key, value] = first;

      if (
        key === 'search' ||
        key === 'location' ||
        key === 'sortByCompany' ||
        key === 'timeframe'
      )
        continue;

      switch (key) {
        case 'workType':
          btns.push({
            text: String(value).replace(/^./, (c) => c.toUpperCase()),
            key: 'workType',
            value: '',
          });
          break;
        case 'level': {
          const levelObj = levelsOptions.find((opt) => opt.value === value);
          btns.push({
            text: levelObj?.label ?? String(value),
            key: 'level',
            value: '',
          });
          break;
        }
        case 'minSalary':
        case 'maxSalary': {
          const foundMin = filterData.find(
            (it) => it && 'minSalary' in it,
          ) as Record<string, unknown> | undefined;
          const foundMax = filterData.find(
            (it) => it && 'maxSalary' in it,
          ) as Record<string, unknown> | undefined;
          const foundCurrency = filterData.find(
            (it) => it && 'currency' in it,
          ) as Record<string, unknown> | undefined;
          const foundTimeframe = filterData.find(
            (it) => it && 'timeframe' in it,
          ) as Record<string, unknown> | undefined;
          const min = foundMin?.minSalary as number | undefined;
          const max = foundMax?.maxSalary as number | undefined;
          const currency = (foundCurrency?.currency as string) ?? '';
          const timeframe = (foundTimeframe?.timeframe as string) ?? '';
          const salaryDisplay = getSalaryDisplay(min, max, currency, timeframe);
          if (salaryDisplay && !btns.some((b) => b.key === 'salary')) {
            btns.push({
              text: salaryDisplay,
              key: 'salary',
              value: {
                minSalary: undefined,
                maxSalary: undefined,
                currency: '',
                timeframe: '',
              },
            });
          }
          break;
        }
        case 'skills':
        case 'markets':
        case 'companySizes':
        case 'contract':
        case 'roles': {
          const arrays: Record<string, string[] | undefined> = {
            skills: filters.skills,
            markets: filters.markets,
            companySizes: filters.companySizes,
            contract: filters.contract,
            roles: filters.roles,
          };
          const arr = arrays[key];
          if (typeof value === 'number') {
            const oneLabel =
              value === 1 && arr?.[0]
                ? key === 'skills'
                  ? skillsOptions.find(
                      (s) => s.toLowerCase().replace(/\s+/g, '-') === arr[0],
                    ) ?? arr[0]
                  : key === 'markets'
                    ? marketsOptions.find(
                        (m) =>
                          m.toLowerCase().replace(/\s+/g, '-') === arr[0],
                      ) ?? arr[0]
                    : arr[0]
                : '';
            btns.push({
              text: value === 1 ? oneLabel : `${key} • ${value}`,
              key,
              value: [],
            });
          } else {
            let label = String(value);
            if (key === 'skills') {
              const found = skillsOptions.find(
                (s) =>
                  s.toLowerCase().replace(/\s+/g, '-') === String(value),
              );
              label = found ?? String(value);
            } else if (key === 'markets') {
              const found = marketsOptions.find(
                (m) =>
                  m.toLowerCase().replace(/\s+/g, '-') === String(value),
              );
              label = found ?? String(value);
            } else if (key === 'roles') {
              const found = rolesOptions.find((r) => r === String(value));
              label = found ?? String(value);
            }
            btns.push({ text: label, key, value: [] });
          }
          break;
        }
        default:
          break;
      }
    }
    return btns;
  }, [filters]);

  const removeBtn = (btnText: string) => {
    const btnToRemove = selectedBtns.find((btn) => btn.text === btnText);
    if (btnToRemove) {
      if (btnToRemove.key === 'salary') {
        dispatch(
          setFilters({
            minSalary: undefined,
            maxSalary: undefined,
            currency: '',
            timeframe: '',
          }),
        );
      } else {
        const key = btnToRemove.key as keyof typeof filters;
        dispatch(setFilters({ [key]: btnToRemove.value } as never));
      }
    }
  };

  const clearAllBtns = () => {
    dispatch(resetFilters());
  };

  return (
    <div
      className={`${
        selectedBtns.length > 0 ? 'block' : 'hidden'
      } border-t pt-5`}
    >
      <div className="w-full relative h-auto">
        <div className="flex flex-wrap gap-4">
          <FilterBtn
            btns={selectedBtns.map((btn) => btn.text)}
            removeBtn={removeBtn}
          />
        </div>
        <button
          type="button"
          className="absolute right-6 top-4 text-teal-600 font-semibold cursor-pointer hover:underline"
          onClick={clearAllBtns}
        >
          Clear
        </button>
      </div>
    </div>
  );
};

export default Filter;
