// client/src/components/filter/SearchAndCountry.vue
<script setup lang="ts">
import { Input } from '@/components/ui/input'
import { MapPin, Search } from 'lucide-vue-next'
import {
  Combobox,
  ComboboxAnchor,
  ComboboxEmpty,
  ComboboxGroup,
  ComboboxInput,
  ComboboxItem,
  ComboboxList,
} from '@/components/ui/combobox'
import { Field, FieldLabel } from '@/components/ui/field'
import { Field as VeeField } from 'vee-validate'
import pycountry from 'countries-list-json'

// Map countries to { value: code, label: name }
const countries = Object.values(pycountry).map((country: any) => ({
  value: country.code,  // Store 2-letter code (NG, US, GB)
  label: country.name   // Display full name (Nigeria, United States)
}))
</script>

<template>
  <div class="flex flex-col sm:flex-row gap-3 w-full">
    <!-- Search Input -->
    <div class="flex-1">
      <VeeField v-slot="{ field, errors, value }" name="search">
        <Field :data-invalid="!!errors.length" class="relative">
          <FieldLabel class="sr-only">Search Jobs</FieldLabel>
          <span class="absolute left-0 inset-y-0 flex items-center px-3 -z-10 w-4">
            <Search class="size-4 text-muted-foreground" />
          </span>
          <Input
            type="text"
            placeholder="Search by role, skill, or company..."
            class="w-full pl-9 h-12 pr-4 py-4 transition-all focus:outline-none focus:ring-2"
            :id="`form-vee-search`"
            :model-value="value"
            :aria-invalid="!!errors.length"
            @update:model-value="field.onChange"
          />
        </Field>
      </VeeField>
    </div>

    <!-- Location Select -->
    <div class="relative flex justify-end">
      <VeeField v-slot="{ field, value }" name="location">
        <Combobox
          :model-value="value"
          @update:model-value="field.onChange"
          class="w-full sm:w-[200px]"
        >
          <ComboboxAnchor>
            <div class="relative w-full max-w-sm items-center">
              <ComboboxInput
                class="pl-9 h-12"
                :display-value="
                  (val) => {
                    const location = countries.find((c) => c.value === val)
                    return location?.label || ''
                  }
                "
                placeholder="Select location..."
              />
              <span class="absolute start-0 inset-y-0 flex items-center justify-center px-3">
                <MapPin class="size-4 text-muted-foreground" />
              </span>
            </div>
          </ComboboxAnchor>
          <ComboboxList>
            <ComboboxEmpty>No location found.</ComboboxEmpty>
            <ComboboxGroup>
              <ComboboxItem
                v-for="location in countries"
                :key="location.value"
                :value="location.value"
              >
                {{ location.label }}
              </ComboboxItem>
            </ComboboxGroup>
          </ComboboxList>
        </Combobox>
      </VeeField>
    </div>
  </div>
</template>

// MERN/client/src/components/filter/SearchAndCountry.tsx
import { useState } from 'react';
import { Search, MapPin } from 'lucide-react';
import countries from 'countries-list-json';

const countryList = Object.values(countries).map((country: any) => ({
  value: country.code,
  label: country.name,
}));

interface SearchAndCountryProps {
  onSearchChange?: (search: string) => void;
  onLocationChange?: (location: string) => void;
  searchValue?: string;
  locationValue?: string;
}

const SearchAndCountry = ({
  onSearchChange,
  onLocationChange,
  searchValue = '',
  locationValue = '',
}: SearchAndCountryProps) => {
  const [search, setSearch] = useState(searchValue);
  const [location, setLocation] = useState(locationValue);
  const [isLocationOpen, setIsLocationOpen] = useState(false);

  const handleSearchChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const value = e.target.value;
    setSearch(value);
    onSearchChange?.(value);
  };

  const handleLocationSelect = (countryCode: string) => {
    setLocation(countryCode);
    setIsLocationOpen(false);
    onLocationChange?.(countryCode);
  };

  const selectedLocation = countryList.find((c) => c.value === location);

  return (
    <div className="flex flex-col sm:flex-row gap-3 w-full">
      {/* Search Input */}
      <div className="flex-1 relative">
        <span className="absolute left-0 inset-y-0 flex items-center px-3 -z-10 w-4">
          <Search className="size-4 text-muted-foreground" />
        </span>
        <input
          type="text"
          placeholder="Search by role, skill, or company..."
          className="w-full pl-9 h-12 pr-4 py-4 transition-all focus:outline-none focus:ring-2 focus:ring-cyan-400 border border-gray-300 rounded-md text-cyan-900"
          value={search}
          onChange={handleSearchChange}
        />
      </div>

      {/* Location Select */}
      <div className="relative flex justify-end">
        <div className="relative w-full sm:w-[200px]">
          <button
            type="button"
            onClick={() => setIsLocationOpen(!isLocationOpen)}
            className="relative w-full pl-9 h-12 pr-4 py-2 border border-gray-300 rounded-md text-left focus:outline-none focus:ring-2 focus:ring-cyan-400 text-cyan-900 bg-white"
          >
            <span className="absolute start-0 inset-y-0 flex items-center justify-center px-3">
              <MapPin className="size-4 text-muted-foreground" />
            </span>
            <span className="block truncate">
              {selectedLocation?.label || 'Select location...'}
            </span>
          </button>

          {isLocationOpen && (
            <div className="absolute z-10 mt-1 w-full bg-white border border-gray-300 rounded-md shadow-lg max-h-60 overflow-auto">
              {countryList.map((country) => (
                <button
                  key={country.value}
                  type="button"
                  onClick={() => handleLocationSelect(country.value)}
                  className="w-full text-left px-4 py-2 hover:bg-cyan-50 text-cyan-900"
                >
                  {country.label}
                </button>
              ))}
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default SearchAndCountry;
