// MERN/client/src/components/filter/CheckboxGroupField.tsx
interface CheckboxGroupFieldProps {
  name: string;
  label: string;
  options: string[];
  value: string[];
  onChange: (value: string[]) => void;
}

const CheckboxGroupField = ({
  name,
  label,
  options,
  value,
  onChange,
}: CheckboxGroupFieldProps) => {
  const toggleOption = (option: string, checked: boolean) => {
    const next = checked ? [...value, option] : value.filter((v) => v !== option);
    onChange(next);
  };

  return (
    <fieldset>
      <legend className="font-bold mb-6 text-cyan-900">{label}</legend>
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-3 text-sm w-full">
        {options.map((opt) => (
          <label
            key={opt}
            htmlFor={`${name}-${opt}`}
            className={`flex flex-row items-center gap-2 border-2 rounded-md p-3 h-[43.25px] cursor-pointer capitalize transition-colors w-full ${
              value.includes(opt)
                ? 'bg-cyan-400/30 border-cyan-900/50 text-cyan-900 font-bold'
                : 'border-gray-200'
            }`}
          >
            <input
              type="checkbox"
              id={`${name}-${opt}`}
              checked={value.includes(opt)}
              onChange={(e: React.ChangeEvent<HTMLInputElement>) =>
                toggleOption(opt, e.target.checked)
              }
              className="accent-cyan-400 rounded"
            />
            <span>{opt}</span>
          </label>
        ))}
      </div>
    </fieldset>
  );
};

export default CheckboxGroupField;

// client/src/components/filter/CheckboxGroupField.vue
<script setup lang="ts">
import { Checkbox } from '@/components/ui/checkbox'
import {
  Field,
  FieldContent,
  FieldGroup,
  FieldLabel,
  FieldLegend,
  FieldSet,
  FieldTitle,
} from '@/components/ui/field'
import { Field as VeeField } from 'vee-validate'

defineProps({
  name: { type: String, required: true },
  label: { type: String, required: true },
  options: { type: Array, required: true },
})
</script>

<template>
  <FieldGroup>
    <VeeField v-slot="{ field, errors, value }" :name="name">
      <FieldSet>
        <FieldLegend class="font-bold mb-6">{{ label }}</FieldLegend>

        <FieldGroup data-slot="checkbox-group" class="grid lg:grid-cols-3 gap-3 text-sm">
          <FieldLabel
            v-for="(option, index) in options"
            :key="index"
            :for="`${name}-${option}`"
            class="!border-2 has-[[data-state=checked]]:!bg-cyan-400/30 has-[[data-state=checked]]:!border-cyan-900/50 has-[[data-state=checked]]:!text-cyan-900/90 has-[[data-state=checked]]:!font-bold capitalize"
          >
            <Field orientation="horizontal" class="flex-row-reverse">
              <FieldContent>
                <FieldTitle>{{ option }}</FieldTitle>
              </FieldContent>

              <Checkbox
                :id="`${name}-${option}`"
                :model-value="value?.includes(option) ?? false"
                :aria-invalid="!!errors.length"
                class="accent-cyan-400"
                @update:model-value="
                  (checked) => {
                    const current = value || []
                    const newValue = checked
                      ? [...current, option]
                      : current.filter((v) => v !== option)
                    field.onChange(newValue)
                  }
                "
              />
            </Field>
          </FieldLabel>
        </FieldGroup>
      </FieldSet>
    </VeeField>
  </FieldGroup>
</template>
