// MERN/client/src/components/filter/RadioGroupField.tsx
interface RadioGroupFieldProps {
  name: string;
  label: string;
  options: string[];
  value: string;
  onChange: (value: string) => void;
  style?: string;
}

const RadioGroupField = ({
  name,
  label,
  options,
  value,
  onChange,
  style = '',
}: RadioGroupFieldProps) => {
  return (
    <div className={style}>
      <fieldset>
        <legend className="font-bold mb-6 text-cyan-900">{label}</legend>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-3 w-full">
          {options.map((option) => (
            <label
              key={option}
              htmlFor={`${name}-${option}`}
              className={`flex flex-row items-center gap-2 border-2 rounded-md p-3 h-10 cursor-pointer capitalize transition-colors w-full ${
                value === option
                  ? 'bg-cyan-400/30 border-cyan-900/50 text-cyan-900 font-bold'
                  : 'border-gray-200'
              }`}
            >
              <input
                type="radio"
                id={`${name}-${option}`}
                name={name}
                value={option}
                checked={value === option}
                onChange={() => onChange(option)}
                className="accent-cyan-400"
              />
              <span className="text-xs">{option}</span>
            </label>
          ))}
        </div>
      </fieldset>
    </div>
  );
};

export default RadioGroupField;

// client/src/components/filter/RadioGroupField.vue
<script setup lang="ts">
import {
    Field,
    FieldContent,
    FieldError,
    FieldGroup,
    FieldLabel,
    FieldLegend,
    FieldSet,
    FieldTitle,
} from '@/components/ui/field'
import { RadioGroup, RadioGroupItem } from '@/components/ui/radio-group'
import { Field as VeeField } from 'vee-validate'

interface Props {
  name: string
  label: string
  options: string[]
  style?: string
}

defineProps<Props>()
</script>

<template>
  <FieldGroup :class="style">
    <VeeField v-slot="{ field, errors }" :name="name">
      <FieldSet>
        <FieldLegend class="font-bold mb-6">{{ label }}</FieldLegend>

        <RadioGroup
          :name="field.name"
          :model-value="field.value"
          :aria-invalid="!!errors.length"
          @update:model-value="field.onChange"
          class="grid grid-cols-3 gap-3"
        >
          <FieldLabel
            v-for="option in options"
            :key="option"
            :for="`${name}-${option}`"
            class="!border-2 has-[[data-state=checked]]:!bg-cyan-400/30 has-[[data-state=checked]]:border-2 has-[[data-state=checked]]:!border-cyan-900/50 has-[[data-state=checked]]:!text-cyan-900/90 has-[[data-state=checked]]:!font-bold capitalize"
          >
            <Field orientation="horizontal" class="flex-row-reverse">
              <FieldContent>
                <FieldTitle>{{ option }}</FieldTitle>
              </FieldContent>
              <RadioGroupItem
                :id="`${name}-${option}`"
                :value="option"
                :aria-invalid="!!errors.length"
                class="accent-cyan-400"
              />
            </Field>
          </FieldLabel>
        </RadioGroup>
        <FieldError v-if="errors.length" :errors="errors" />
      </FieldSet>
    </VeeField>
  </FieldGroup>
</template>
