// MERN/client/src/components/filter/SalaryRangeInput.tsx
import type { ReactNode } from 'react';

interface SalaryRangeInputProps {
  minSalary: number | undefined;
  maxSalary: number | undefined;
  onMinSalaryChange: (value: number | undefined) => void;
  onMaxSalaryChange: (value: number | undefined) => void;
  salaryError?: string;
  currencySlot: ReactNode;
  timeframeSlot: ReactNode;
}

const SalaryRangeInput = ({
  minSalary,
  maxSalary,
  onMinSalaryChange,
  onMaxSalaryChange,
  salaryError,
  currencySlot,
  timeframeSlot,
}: SalaryRangeInputProps) => {
  return (
    <div className="space-y-4 flex">
      <div className="flex items-center justify-between sr-only">
        <span className="text-cyan-900">Compensation</span>
      </div>
      <div className="flex flex-col sm:flex-row gap-4 relative">
        <div className="flex gap-4 items-center h-fit">
          <div className="relative">
            <label htmlFor="form-vee-demo-minSalary" className="sr-only">
              Min Salary
            </label>
            <input
              type="number"
              id="form-vee-demo-minSalary"
              placeholder="Min"
              min={0}
              value={minSalary ?? ''}
              onChange={(e) =>
                onMinSalaryChange(
                  e.target.value === '' || e.target.value === null
                    ? undefined
                    : Number(e.target.value),
                )
              }
              className="w-24 h-12 py-1 px-3 border border-gray-200 rounded-md transition-all focus:outline-none focus:border-gray-400 text-cyan-900 placeholder:text-slate-400"
            />
          </div>
          <span className="text-gray-500">-</span>
          <div className="relative">
            <label htmlFor="form-vee-demo-maxSalary" className="sr-only">
              Max Salary
            </label>
            <input
              type="number"
              id="form-vee-demo-maxSalary"
              placeholder="Max"
              min={0}
              value={maxSalary ?? ''}
              onChange={(e) =>
                onMaxSalaryChange(
                  e.target.value === '' || e.target.value === null
                    ? undefined
                    : Number(e.target.value),
                )
              }
              className="w-24 h-12 py-1 px-3 border border-gray-200 rounded-md transition-all focus:outline-none focus:border-gray-400 text-cyan-900 placeholder:text-slate-400"
            />
          </div>
        </div>
        <div className="flex flex-col sm:flex-row gap-4 w-full">
          {currencySlot}
          {timeframeSlot}
        </div>
        {salaryError && (
          <p className="absolute -top-6 left-0 text-xs italic text-red-400">{salaryError}</p>
        )}
      </div>
    </div>
  );
};

export default SalaryRangeInput;

// client/src/components/filter/SalaryRangeInput.vue
<script setup lang="ts">
import { Field, FieldLabel } from '@/components/ui/field'
import { Field as VeeField, ErrorMessage } from 'vee-validate'
import Input from '../ui/input/Input.vue'
</script>

<template>
  <div class="space-y-4 flex">
    <div class="flex items-center justify-between sr-only">
      <FieldLabel class="text-cyan-900">Compensation</FieldLabel>
    </div>

    <div class="flex flex-col sm:flex-row gap-4 relative">
      <!-- Min Salary -->
      <div class="flex gap-4 items-center h-fit">
        <VeeField v-slot="{ field, errors, value }" name="minSalary">
          <Field :data-invalid="!!errors.length" class="relative">
            <FieldLabel class="sr-only">Min Salary</FieldLabel>
            <Input
              type="number"
              placeholder="Min"
              :id="`form-vee-demo-minSalary`"
              :model-value="value"
              :aria-invalid="!!errors.length"
              class="w-24 h-12 px-3 transition-all focus:outline-none focus:ring-2"
              @update:model-value="
                (val) => field.onChange(val === '' || val === null ? undefined : Number(val))
              "
              @blur="field.onBlur"
            />
          </Field>
        </VeeField>
        <span class="text-gray-500">-</span>
        <!-- Max Salary -->
        <VeeField v-slot="{ field, errors, value }" name="maxSalary">
          <Field :data-invalid="!!errors.length" class="relative">
            <FieldLabel class="sr-only">Max Salary</FieldLabel>
            <Input
              :id="`form-vee-demo-maxSalary`"
              type="number"
              :model-value="value"
              :aria-invalid="!!errors.length"
              placeholder="Max"
              class="w-24 h-12 px-3 transition-all focus:outline-none focus:ring-2"
              @update:model-value="
                (val) => field.onChange(val === '' || val === null ? undefined : Number(val))
              "
              @blur="field.onBlur"
            />
          </Field>
        </VeeField>
      </div>
      <div class="flex flex-col sm:flex-row gap-4 w-full">
        <slot name="currency" />
        <slot name="timeframe" />
      </div>
      <ErrorMessage name="maxSalary" v-slot="{ message }">
        <p
          v-if="message"
          class="absolute -top-6 left-0 text-xs italic text-red-400"
        >
          {{ message }}
        </p>
      </ErrorMessage>
    </div>
  </div>
</template>
