// MERN/client/src/components/filter/SelectField.tsx
export interface SelectOption {
  value: string;
  label: string;
}

interface SelectFieldProps {
  name: string;
  label: string;
  options: SelectOption[];
  placeholder?: string;
  value: string;
  onChange: (value: string) => void;
  style?: string;
}

const SelectField = ({
  name,
  label,
  options,
  placeholder = 'Select',
  value,
  onChange,
  style = '',
}: SelectFieldProps) => {
  return (
    <div className={style}>
      <div className="gap-0">
        <label htmlFor={`form-vee-select-${name}`} className="sr-only">
          {label}
        </label>
        <select
          id={`form-vee-select-${name}`}
          value={value}
          onChange={(e) => onChange(e.target.value)}
          className={`min-w-[120px] h-12 py-1 px-3 border border-gray-200 rounded-md focus:outline-none focus:border-gray-400 text-cyan-900 ${value === '' ? 'text-slate-400' : ''}`}
        >
          <option value="" className="text-slate-400">{placeholder}</option>
          {options.map((opt) => (
            <option key={opt.value} value={opt.value}>
              {opt.label}
            </option>
          ))}
        </select>
      </div>
    </div>
  );
};

export default SelectField;

// client/src/components/filter/SelectField.vue
<script setup lang="ts">
import { Field, FieldContent, FieldError, FieldGroup, FieldLabel } from '@/components/ui/field'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import { Field as VeeField } from 'vee-validate'

interface Option {
  value: string
  label: string
}

interface Props {
  name: string
  label: string
  options: Option[]
  placeholder?: string
  style?: string
}

withDefaults(defineProps<Props>(), {
  placeholder: 'Select',
  style: '',
})
</script>

<template>
  <FieldGroup :class="style">
    <VeeField v-slot="{ field, errors, value }" :name="name">
      <Field orientation="responsive" :data-invalid="!!errors.length" class="gap-0">
        <FieldContent class="sr-only">
          <FieldLabel :for="`form-vee-select-${name}`">{{ label }}</FieldLabel>
          <FieldError v-if="errors.length" :errors="errors" />
        </FieldContent>

        <Select :name="field.name" :model-value="value" @update:model-value="field.onChange">
          <SelectTrigger
            :id="`form-vee-select-${name}`"
            :aria-invalid="!!errors.length"
            class="min-w-[120px] h-12"
          >
            <SelectValue :placeholder="placeholder">
              {{ options.find((opt) => opt.value === value)?.label || placeholder }}
            </SelectValue>
          </SelectTrigger>

          <SelectContent position="item-aligned">
            <SelectItem v-for="option in options" :key="option.value" :value="option.value">
              {{ option.label }}
            </SelectItem>
          </SelectContent>
        </Select>
      </Field>
    </VeeField>
  </FieldGroup>
</template>
